### ISSUE TITLE
Getting Typescript Error

### ISSUE THREAD

**Issue by wesleyjayfrisby** [jperelli/vue2-leaflet-googlemutant#47]
I am getting this error: 
Uncaught (in promise) TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function

I attached our implementation along with where in the JS it is breaking 

This seemed to have started without any code changes and the version of googlemutant also wasn't changed (2.0.0)

Edit: This error is also on the sample project

![image](https://github.com/user-attachments/assets/d6dd1a77-f9c9-4726-a456-0de6cdb54687)
![image](https://github.com/user-attachments/assets/328cc331-e94e-471e-9207-1be7df7acb9e)
![image](https://github.com/user-attachments/assets/dfec539c-2a38-460a-a647-5fac3bb68baa)

**Comment by AntMam** [comment]
Having same issue

**Comment by wesleyjayfrisby** [comment]
> Having same issue

Managed to solve it by adding styles: [] in options
